version: '3.8'

services:
  spigot:
    build: .
    ports:
      - "25565:25565"  # Minecraft server port
    volumes:
      - ./data:/data  # Mount server data directory
      - ./plugins:/data/plugins  # Mount plugins directory
    environment:
      - EULA=TRUE
      - MEMORY=2G
    restart: unless-stopped
    tty: true
    stdin_open: true 