version: '3.8'

services:
  spigot:
    build: .
    ports:
      - "25565:25565"  # Minecraft server port
      - "19132:19132/udp"  # Bedrock port
      - "19133:19133/udp"  # Bedrock port
      - "19132:19132/tcp"  # Geyser port
      - "19133:19133/tcp"  # Geyser port
      - "25575:25575"
    volumes:
      - ./data:/data  # Mount server data directory
    environment:
      - EULA=TRUE
      - MEMORY=2G
    restart: unless-stopped
    tty: true
    stdin_open: true 